/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceCustomersRouteImport } from './routes/service/customers'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ServiceCustomersCustomerIdRouteImport } from './routes/service/customers.$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCustomersRoute = ServiceCustomersRouteImport.update({
  id: '/service/customers',
  path: '/service/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCustomersCustomerIdRoute =
  ServiceCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => ServiceCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/service/customers': typeof ServiceCustomersRouteWithChildren
  '/service/customers/$customerId': typeof ServiceCustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/service/customers': typeof ServiceCustomersRouteWithChildren
  '/service/customers/$customerId': typeof ServiceCustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/service/customers': typeof ServiceCustomersRouteWithChildren
  '/service/customers/$customerId': typeof ServiceCustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/users'
    | '/auth/login'
    | '/service/customers'
    | '/service/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/users'
    | '/auth/login'
    | '/service/customers'
    | '/service/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/admin/users'
    | '/auth/login'
    | '/service/customers'
    | '/service/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthLoginRoute: typeof AuthLoginRoute
  ServiceCustomersRoute: typeof ServiceCustomersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/customers': {
      id: '/service/customers'
      path: '/service/customers'
      fullPath: '/service/customers'
      preLoaderRoute: typeof ServiceCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/customers/$customerId': {
      id: '/service/customers/$customerId'
      path: '/$customerId'
      fullPath: '/service/customers/$customerId'
      preLoaderRoute: typeof ServiceCustomersCustomerIdRouteImport
      parentRoute: typeof ServiceCustomersRoute
    }
  }
}

interface ServiceCustomersRouteChildren {
  ServiceCustomersCustomerIdRoute: typeof ServiceCustomersCustomerIdRoute
}

const ServiceCustomersRouteChildren: ServiceCustomersRouteChildren = {
  ServiceCustomersCustomerIdRoute: ServiceCustomersCustomerIdRoute,
}

const ServiceCustomersRouteWithChildren =
  ServiceCustomersRoute._addFileChildren(ServiceCustomersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthLoginRoute: AuthLoginRoute,
  ServiceCustomersRoute: ServiceCustomersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
